name: Checking Lint and build Image on PR

on: 
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: List Directory
      run: find .
    - name: Analysing the code with pylint
      run: |
        python -m pipenv run pylint `find . |grep .py$ | xargs`
